##################
# Notif to slack # 
##################
receivers:
  - name: 'devops'
    slack_configs:
    - channel: alerts
      send_resolved: true
      api_url: https://hooks.slack.com/services/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
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Notification'
      text: >-
        {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
          *Description:* {{ .Annotations.description }}
          *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
          *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}
